### ISSUE TITLE
Change doc for co-first author

### ISSUE THREAD

**Issue by pdebuyl** [openjournals/joss#1081]
Hi,

In https://github.com/JamesPHoughton/pysd/issues/316 the authors refer to the "old" co-first-authorship syntax.

Apparently it has changed (see https://github.com/openjournals/joss-reviews/issues/4158#issuecomment-1105398633 ).

Can we update the sample paper with the new syntax? Ditto for corresponding author of course.

```
---
title: 'Gala: A Python package for galactic dynamics'
tags:
  - Python
  - astronomy
  - dynamics
  - galactic dynamics
  - milky way
authors:
  - name: Adrian M. Price-Whelan
    orcid: 0000-0000-0000-0000
    equal-contrib: true
    affiliation: "1, 2" # (Multiple affiliations must be quoted)
  - name: Author Without ORCID
    equal-contrib: true
    affiliation: 2
  - name: Author with no affiliation
    corresponding: true
    affiliation: 3
affiliations:
 - name: Lyman Spitzer, Jr. Fellow, Princeton University, USA
   index: 1
 - name: Institution Name, Country
   index: 2
 - name: Independent Researcher, Country
   index: 3
date: 13 August 2017
bibliography: paper.bib

# Optional fields if submitting to a AAS journal too, see this blog post:
# https://blog.joss.theoj.org/2018/12/a-new-collaboration-with-aas-publishing
aas-doi: 10.3847/xxxxx <- update this with the DOI from AAS once you know it.
aas-journal: Astrophysical Journal <- The name of the AAS journal.
---
```
PS: in case it is convenient, feel free to copy-paste the above. I copy-pasted from the doc and from the linked issue.
