### ISSUE TITLE
"These authors contributed equally to this work"

### ISSUE THREAD

**Issue by CJ-Wright** [openjournals/joss#337]
In some journals it is common to add a statement to the effect of "Foo Smith*, Jane Bar*, PI Name(s) *These authors contributed equally to this work." Is that possible with JOSS?
@sbillinge

**Comment by arfon** [comment]
There isn't any special area in the paper where this would be included but perhaps you could include a statement in the paper somewhere?

**Comment by lskatz** [comment]
Hi @CJ-Wright and @arfon , I know this ticket is years old now, but is there a standard way to notate equal contributions now?

**Comment by danielskatz** [comment]
I wrote https://danielskatzblog.wordpress.com/2020/10/16/authorship-tiers/ about this topic about a week ago, and mentioned https://doi.org/10.21105/joss.02579 as a recent JOSS publication that did this, but I don't think there's a standard way.

**Comment by lskatz** [comment]
Wonderful, thank you @danielskatz !  This looks very straightforward (pasting for posterity)!

```
authors:
    - name: John Hoffer^[co-first author]
      orcid: 0000-0002-5877-4266
      affiliation: 1
    - name: Rumana Rashid^[co-first author]
      orcid: 0000-0001-6986-7209
      affiliation: "1, 2, 3"
    - name: Jeremy L. Muhlich
      orcid: 0000-0002-0811-637X
      affiliation: 1
    - name: Yu-An Chen
      orcid: 0000-0001-7228-4696
      affiliation: "1, 2"
    - name: Douglas Peter William Russell
      orcid: 0000-0001-7446-2353
      affiliation: 4
    - name: Juha Ruokonen
      orcid: 0000-0002-6381-121X
      affiliation: 1
    - name: Robert Krueger
      orcid: 0000-0002-6468-8356
      affiliation: "1, 5"
    - name: Hanspeter Pfister
      orcid: 0000-0002-3620-2582
      affiliation: 5
    - name: Sandro Santagata
      orcid: 0000-0002-7528-9668
      affiliation: "1, 2, 3"
    - name: Peter K. Sorger^[corresponding author]
      orcid: 0000-0002-3364-1838
      affiliation: "1, 2, 6"
```

![image](https://user-images.githubusercontent.com/14798/97053460-ffe9a000-1550-11eb-9770-5bd8c3ea9e29.png)
---
![image](https://user-images.githubusercontent.com/14798/97053477-07a94480-1551-11eb-9eaa-9905e13168b5.png)
