### ISSUE TITLE
Submit bibliography file in CSL format?

### ISSUE THREAD

**Issue by bwiernik** [openjournals/joss#935]
I was wondering whether it was acceptable to submit the bibliography file for the paper in CSL format (CSL YAML or CSL JSON)? CSL is pandoc's native bibliographic data format. Any other format, such as .bib or RIS, is converted internally to CSL YAML when pandoc generates citations. This isn't a perfect process (.bib is a less expressive language than CSL), and citations to non-journal/book items (e.g., to datasets, software, reports, or media items) will often be somewhat incorrect pandoc citations when created from a .bib file versus a CSL .yaml file. 

An example CSL YAML item is below:

```
---
references:
- id: CuddebackDetectingstatisticallycorrecting2004
  accessed:
    - year: 2018
      month: 11
      day: 3
  author:
    - family: Cuddeback
      given: Gary
    - family: Wilson
      given: Elizabeth
    - family: Orme
      given: John G.
    - family: Combs-Orme
      given: Terri
  container-title: Journal of Social Service Research
  DOI: 10.1300/j079v30n03_02
  ISSN: 0148-8376, 1540-7314
  issue: '3'
  issued:
    - year: 2004
      month: 5
      day: 10
  language: en
  page: 19-33
  source: Crossref
  title: Detecting and statistically correcting sample selection bias
  type: article-journal
  URL: http://www.tandfonline.com/doi/abs/10.1300/J079v30n03_02
  volume: '30'
...
```
